#!/usr/bin/env bash
set -e

cd ../brefsearch-media
rsync \
  --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --copy-links \
  --compress \
  ./media/* \
  pixelastic:/var/www/assets.pixelastic.com/brefsearch
